# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-x86:
    docker:
      - image: "cimg/base:stable-20.04"
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'sudo apt-get update && sudo apt-get install -y && sudo rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'sudo apt-get update && sudo apt-get install -y gcc-9 g++'
      - run:
          name: Install CMAKE
          command: 'sudo apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Build
          command: |
            cmake -DCMAKE_BUILD_TYPE=Release -S ./ -B ./build
            cd ./build
            make
      - run:
          name: Test
          command: |
            cd ../bin/Release
            ./cavlc_test
  build-arm:
    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - run:
          name: Build
          command: |
            cmake -DCMAKE_BUILD_TYPE=Release -S ./ -B ./build
            cd ./build
            make
      - run:
          name: Test
          command: |
            cd ../bin/Release
            ./cavlc_test
